# Generated by Django 4.1.2 on 2022-11-04 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiPlayer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_part_one', models.CharField(blank=True, max_length=350, null=True, verbose_name='Questions I')),
                ('question_part_one_tagalog', models.CharField(blank=True, max_length=350, null=True, verbose_name='Tagalog')),
            ],
            options={
                'verbose_name': 'Demographics Question I',
                'verbose_name_plural': 'Demographics Question I',
            },
        ),
        migrations.CreateModel(
            name='DemographicsTwoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_part_two', models.CharField(blank=True, max_length=350, null=True, verbose_name='Questions II')),
                ('question_part_two_tagalog', models.CharField(blank=True, max_length=350, null=True, verbose_name='Tagalog')),
            ],
            options={
                'verbose_name': 'Demographics Question II',
                'verbose_name_plural': 'Demographics Question II',
            },
        ),
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Pre Assess ID')),
                ('questions', models.CharField(max_length=350, verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Personality Test',
                'verbose_name_plural': 'Personality Test',
            },
        ),
        migrations.CreateModel(
            name='PreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('+', 'Addition'), ('-', 'Subtraction'), ('×', 'Multiplication'), ('÷', 'Division')], max_length=50, verbose_name='Arithmetic Operators')),
                ('q1', models.CharField(max_length=50, verbose_name='q1')),
                ('q11', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Optional')),
                ('q2', models.CharField(max_length=50, verbose_name='q2')),
                ('q22', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Optional')),
                ('answer', models.CharField(max_length=50, verbose_name='answer')),
            ],
            options={
                'verbose_name': 'Pre Test Question',
            },
        ),
        migrations.CreateModel(
            name='ResearchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_mode', models.BooleanField(default=True, verbose_name='Research Mode')),
            ],
            options={
                'verbose_name': 'Research Mode',
                'verbose_name_plural': 'Research Mode',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='Username')),
                ('surname', models.CharField(max_length=250, verbose_name='Surname')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('section', models.CharField(blank=True, max_length=250, null=True, verbose_name='Section')),
                ('user_session', models.CharField(max_length=150, null=True, verbose_name='User Session')),
                ('demographics', models.TextField(blank=True, verbose_name='Demographics')),
                ('personality_test', models.TextField(blank=True, verbose_name='Personality Test')),
                ('pre_test_answer', models.TextField(blank=True, verbose_name='Pre-Test Answers')),
                ('pre_test_score', models.CharField(blank=True, max_length=150, verbose_name='Pre-test Score')),
                ('game_scores', models.TextField(blank=True, verbose_name='Game Scores')),
                ('game_answer_history', models.TextField(blank=True, verbose_name='Game Answers')),
                ('speed', models.CharField(blank=True, max_length=250, null=True, verbose_name='Speed')),
                ('total_questions', models.CharField(blank=True, max_length=250, null=True, verbose_name='Total Questions')),
                ('correct_answers', models.CharField(blank=True, max_length=250, null=True, verbose_name='Correct Answers')),
                ('wrong_answers', models.CharField(blank=True, max_length=250, null=True, verbose_name='Wrong Answers')),
                ('player_mode', models.CharField(blank=True, max_length=250, null=True, verbose_name='Player Mode')),
                ('is_pending', models.BooleanField(default=True, verbose_name='Pending')),
                ('date', models.DateField(null=True)),
                ('group', models.ForeignKey(blank=True, default=None, help_text='Add Group for your student', null=True, on_delete=django.db.models.deletion.PROTECT, to='multiPlayer.group')),
            ],
        ),
    ]
